<a href="https://colab.research.google.com/github/sid1309/MediSense/blob/main/MediSense.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

#import Model
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier , GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix


In [3]:
dataset = pd.read_csv('/content/drive/MyDrive/MediSense/Training.csv')

In [4]:
dataset


itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  blackheads  scurring  skin_peeling  silver_like_dusting  \
0     ...           0         0             0                    0   
1     ...           0         0             0                    0   
2     ...           0         0             0                    0   
3     ...           0         0             0                    0   
4     ...           0         0             0                    0   
...   ...         ...       ...           ...                  ...   
4915  ...           0         0             0                    0   
4916  ...           1         1             0                    0   
4917  ...           0         0             0                    0   
4918  ...           0         0             1                    1   
4919  ...           0         0             0                    0   

      small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                        0                   0        0                     0   
1                        0                   0        0                     0   
2                        0                   0        0                     0   
3                        0                   0        0                     0   
4                        0                   0        0                     0   
...                    ...                 ...      ...                   ...   
4915                     0                   0        0                     0   
4916                     0                   0        0                     0   
4917                     0                   0        0                     0   
4918                     1                   1        0                     0   
4919                     0                   0        1                     1   

      yellow_crust_ooze                                prognosis  
0                     0                         Fungal infection  
1                     0                         Fungal infection  
2                     0                         Fungal infection  
3                     0                         Fungal infection  
4                     0                    

In [5]:
dataset.shape


(4920, 133)

In [6]:
dataset.isnull().sum()

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

In [7]:
dataset.describe()

itching    skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count  4920.000000  4920.000000           4920.000000          4920.000000   
mean      0.137805     0.159756              0.021951             0.045122   
std       0.344730     0.366417              0.146539             0.207593   
min       0.000000     0.000000              0.000000             0.000000   
25%       0.000000     0.000000              0.000000             0.000000   
50%       0.000000     0.000000              0.000000             0.000000   
75%       0.000000     0.000000              0.000000             0.000000   
max       1.000000     1.000000              1.000000             1.000000   

         shivering       chills   joint_pain  stomach_pain      acidity  \
count  4920.000000  4920.000000  4920.000000   4920.000000  4920.000000   
mean      0.021951     0.162195     0.139024      0.045122     0.045122   
std       0.146539     0.368667     0.346007      0.207593     0.207593   
min       0.000000     0.000000     0.000000      0.000000     0.000000   
25%       0.000000     0.000000     0.000000      0.000000     0.000000   
50%       0.000000     0.000000     0.000000      0.000000     0.000000   
75%       0.000000     0.000000     0.000000      0.000000     0.000000   
max       1.000000     1.000000     1.000000      1.000000     1.000000   

       ulcers_on_tongue  ...  pus_filled_pimples   blackheads     scurring  \
count       4920.000000  ...         4920.000000  4920.000000  4920.000000   
mean           0.021951  ...            0.021951     0.021951     0.021951   
std            0.146539  ...            0.146539     0.146539     0.146539   
min            0.000000  ...            0.000000     0.000000     0.000000   
25%            0.000000  ...            0.000000     0.000000     0.000000   
50%            0.000000  ...            0.000000     0.000000     0.000000   
75%            0.000000  ...            0.000000     0.000000     0.000000   
max            1.000000  ...            1.000000     1.000000     1.000000   

       skin_peeling  silver_like_dusting  small_dents_in_nails  \
count   4920.000000          4920.000000           4920.000000   
mean       0.023171             0.023171              0.023171   
std        0.150461             0.150461              0.150461   
min        0.000000             0.000000              0.000000   
25%        0.000000             0.000000              0.000000   
50%        0.000000             0.000000              0.000000   
75%        0.000000             0.000000              0.000000   
max        1.000000             1.000000              1.000000   

       inflammatory_nails      blister  red_sore_around_nose  \
count         4920.000000  4920.000000           4920.000000   
mean             0.023171     0.023171              0.023171   
std              0.150461     0.150461              0.150461   
min              0.000000     0.000000              0.000000   
25%              0.000000     0.000000              0.000000   
50%              0.000000     0.000000              0.000000   
75%              0.000000     0.000000              0.000000   
max              1.000000     1.000000              1.000000   

       yellow_crust_ooze  
count        4920.000000  
mean            0.023171  
std             0.150461  
min             0.000000  
25%             0.000000  
50%             0.000000  
75%             0.000000  
max             1.000000  

[8 rows x 132 columns]

In [8]:
dataset.head(2)

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  

[2 rows x 133 columns]

In [9]:
dataset.prognosis.value_counts()

prognosis
Fungal infection                           120
Hepatitis C                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Hepatitis D                                120
Hepatitis B                                120
Allergy                                    120
hepatitis A                                120
GERD                                       120
Chronic cholestasis                        120
Drug Reaction                              120
Peptic ulcer diseae                        120
AIDS                                       120
Diabetes                                   120
Gastroenteritis                            120
Bronchial Asthma                           120
Hypertension                               120
Migraine                                   120
Cervical spondylosis                       120
Paralysis (brain hemorrhage)               120
Jaundice                                   120
Malaria                                    120
Chicken pox                                120
Dengue                                     120
Typhoid                                    120
Impetigo                                   120
Name: count, dtype: int64

In [10]:
#total number of unique diseases
len(dataset.prognosis.value_counts())

41

In [11]:
dataset.prognosis.unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [12]:
print(f"Number of duplicates in dataset: {dataset.duplicated().sum()}")

Number of duplicates in dataset: 4616


In [13]:
dataset = dataset.drop_duplicates()

In [14]:
print(f"Number of duplicates in dataset: {dataset.duplicated().sum()}")

Number of duplicates in dataset: 0


In [15]:
X= dataset.drop('prognosis',axis=1)
y=dataset['prognosis']

In [16]:
le=LabelEncoder().fit(y)
Y=le.transform(y)

In [17]:
Y

array([15, 15, 15, 15, 15,  4,  4,  4,  4,  4, 16, 16, 16, 16, 16, 16, 16,
        9,  9,  9,  9,  9,  9,  9,  9, 14, 14, 14, 14, 14, 14, 33, 33, 33,
       33, 33, 33, 33,  1,  1,  1,  1,  1, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 17, 17, 17, 17, 17,  6,  6,  6,  6,  6,  6,  6, 23, 23, 23, 23,
       23, 23, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,  7,  7,  7,  7,  7,
        7, 32, 32, 32, 32, 32, 28, 28, 28, 28, 28, 28, 28, 28, 28, 29, 29,
       29, 29, 29, 29, 29, 29,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 37, 37, 37, 37, 37, 37, 37, 37,
       37, 40, 40, 40, 40, 40, 40, 40, 40, 40, 19, 19, 19, 19, 19, 19, 19,
       19, 19, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21, 21, 21,
       21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22,  3,  3,  3,  3,  3,  3,
        3,  3, 36, 36, 36, 36, 36, 36, 36, 36, 36, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 34, 34, 34, 34, 34, 34, 34, 34, 34, 13, 13, 13, 13, 13,
       13, 18, 18, 18, 18

In [18]:
X

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0          1          1                     1                    0          0   
1          0          1                     1                    0          0   
2          1          0                     1                    0          0   
3          1          1                     0                    0          0   
4          1          1                     1                    0          0   
..       ...        ...                   ...                  ...        ...   
402        0          0                     0                    0          0   
403        0          1                     0                    0          0   
405        0          1                     0                    0          0   
406        0          1                     0                    0          0   
407        0          1                     0                    0          0   

     chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0         0           0             0        0                 0  ...   
1         0           0             0        0                 0  ...   
2         0           0             0        0                 0  ...   
3         0           0             0        0                 0  ...   
4         0           0             0        0                 0  ...   
..      ...         ...           ...      ...               ...  ...   
402       0           0             0        0                 0  ...   
403       0           0             0        0                 0  ...   
405       0           0             0        0                 0  ...   
406       0           0             0        0                 0  ...   
407       0           0             0        0                 0  ...   

     pus_filled_pimples  blackheads  scurring  skin_peeling  \
0                     0           0         0             0   
1                     0           0         0             0   
2                     0           0         0             0   
3                     0           0         0             0   
4                     0           0         0             0   
..                  ...         ...       ...           ...   
402                   0           0         0             0   
403                   0           0         0             0   
405                   0           0         0             0   
406                   0           0         0             0   
407                   0           0         0             0   

     silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                      0                     0                   0        0   
1                      0                     0                   0        0   
2                      0                     0                   0        0   
3                      0                     0                   0        0   
4                      0                     0                   0        0   
..                   ...                   ...                 ...      ...   
402                    0                     0                   0        1   
403                    0                     0                   0        1   
405                    0                     0                   0        0   
406                    0                     0                   0        1   
407                    0                     0                   0        1   

     red_sore_around_nose  yellow_crust_ooze  
0                       0                  0  
1                       0                  0  
2                       0                  0  
3                       0                  0  
4                       0                  0  
..                    ...                ...  
402                     1                  1  
403                     1                  1  
405                     1 

Training

In [19]:
Y.shape



(304,)

In [20]:
X.shape

(304, 132)

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.2,random_state=42 , stratify =y)

In [22]:
X_train

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
196        0          0                     0                    0          0   
396        0          1                     0                    0          0   
326        0          0                     0                    0          0   
173        0          1                     0                    0          0   
151        0          0                     0                    0          0   
..       ...        ...                   ...                  ...        ...   
61         0          0                     0                    0          0   
83         0          0                     0                    0          0   
168        1          1                     0                    0          0   
186        0          0                     0                    0          0   
406        0          1                     0                    0          0   

     chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
196       0           1             0        0                 0  ...   
396       0           1             0        0                 0  ...   
326       0           0             0        0                 0  ...   
173       1           1             0        0                 0  ...   
151       1           0             0        0                 0  ...   
..      ...         ...           ...      ...               ...  ...   
61        0           0             0        0                 0  ...   
83        0           0             0        0                 0  ...   
168       0           0             0        0                 0  ...   
186       1           0             0        0                 0  ...   
406       0           0             0        0                 0  ...   

     pus_filled_pimples  blackheads  scurring  skin_peeling  \
196                   0           0         0             0   
396                   0           0         0             1   
326                   0           0         0             0   
173                   0           0         0             0   
151                   0           0         0             0   
..                  ...         ...       ...           ...   
61                    0           0         0             0   
83                    0           0         0             0   
168                   0           0         0             0   
186                   0           0         0             0   
406                   0           0         0             0   

     silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
196                    0                     0                   0        0   
396                    1                     0                   1        0   
326                    0                     0                   0        0   
173                    0                     0                   0        0   
151                    0                     0                   0        0   
..                   ...                   ...                 ...      ...   
61                     0                     0                   0        0   
83                     0                     0                   0        0   
168                    0                     0                   0        0   
186                    0                     0                   0        0   
406                    0                     0                   0        1   

     red_sore_around_nose  yellow_crust_ooze  
196                     0                  0  
396                     0                  0  
326                     0                  0  
173                     0                  0  
151                     0                  0  
..                    ...                ...  
61                      0                  0  
83                      0                  0  
168                     0 

In [23]:
X_test

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
209        1          0                     0                    0          0   
273        0          0                     0                    0          0   
40         1          1                     0                    0          0   
10         0          0                     0                    1          1   
276        0          0                     0                    0          0   
..       ...        ...                   ...                  ...        ...   
80         0          0                     0                    0          0   
176        0          1                     0                    0          0   
244        0          0                     0                    0          0   
117        0          0                     0                    0          0   
248        0          0                     0                    0          0   

     chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
209       0           0             0        0                 0  ...   
273       0           0             0        0                 0  ...   
40        0           0             1        0                 0  ...   
10        1           0             0        0                 0  ...   
276       1           0             0        0                 0  ...   
..      ...         ...           ...      ...               ...  ...   
80        0           0             0        0                 0  ...   
176       1           0             0        0                 0  ...   
244       0           0             0        0                 0  ...   
117       0           0             0        1                 0  ...   
248       0           0             0        0                 0  ...   

     pus_filled_pimples  blackheads  scurring  skin_peeling  \
209                   0           0         0             0   
273                   0           0         0             0   
40                    0           0         0             0   
10                    0           0         0             0   
276                   0           0         0             0   
..                  ...         ...       ...           ...   
80                    0           0         0             0   
176                   0           0         0             0   
244                   0           0         0             0   
117                   0           0         0             0   
248                   0           0         0             0   

     silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
209                    0                     0                   0        0   
273                    0                     0                   0        0   
40                     0                     0                   0        0   
10                     0                     0                   0        0   
276                    0                     0                   0        0   
..                   ...                   ...                 ...      ...   
80                     0                     0                   0        0   
176                    0                     0                   0        0   
244                    0                     0                   0        0   
117                    0                     0                   0        0   
248                    0                     0                   0        0   

     red_sore_around_nose  yellow_crust_ooze  
209                     0                  0  
273                     0                  0  
40                      0                  0  
10                      0                  0  
276                     0                  0  
..                    ...                ...  
80                      0                  0  
176                     0                  0  
244                     0 

In [24]:
models = {
    'SVC': SVC(kernel = 'linear'),
    'Random_forest' : RandomForestClassifier(n_estimators= 100 , random_state=2),
    'Gradiant_Boosting': GradientBoostingClassifier(n_estimators=100 , random_state = 2),
    'MultiNomialNB' : MultinomialNB(),
    'Kneighbours': KNeighborsClassifier(n_neighbors= 5 )
}

for model_name , model in models.items():
    model.fit(X_train,y_train)

    y_pred=model.predict(X_test)
    accuracy=accuracy_score(y_test , y_pred)
    cm= confusion_matrix(y_test,y_pred)
    print('--------------------------------')
    print(f"{model_name} accuracy:{accuracy}")
    print(f"{model_name} Confusion_matrics: {cm}")
    print(np.array2string(cm, separator = ",") )

--------------------------------
SVC accuracy:1.0
SVC Confusion_matrics: [[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 0 0 2]]
[[1,0,0,...,0,0,0],
 [0,1,0,...,0,0,0],
 [0,0,1,...,0,0,0],
 ...,
 [0,0,0,...,1,0,0],
 [0,0,0,...,0,2,0],
 [0,0,0,...,0,0,2]]
--------------------------------
Random_forest accuracy:1.0
Random_forest Confusion_matrics: [[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 0 0 2]]
[[1,0,0,...,0,0,0],
 [0,1,0,...,0,0,0],
 [0,0,1,...,0,0,0],
 ...,
 [0,0,0,...,1,0,0],
 [0,0,0,...,0,2,0],
 [0,0,0,...,0,0,2]]
--------------------------------
Gradiant_Boosting accuracy:0.8360655737704918
Gradiant_Boosting Confusion_matrics: [[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 0 0 2]]
[[1,0,0,...,0,0,0],
 [0,0,0,...,0,0,0],
 [0,0,0,...,0,0,0],
 ...,
 [0,0,0,...,0,0,0],
 [0,0,0,...,0,2,0],


In [25]:
from sklearn.model_selection import cross_val_score

for model_name, model in models.items():
    scores = cross_val_score(model, X, y, cv=5)
    print(f"{model_name} cross-validation accuracy: {scores.mean():.4f}")


SVC cross-validation accuracy: 1.0000
Random_forest cross-validation accuracy: 1.0000
Gradiant_Boosting cross-validation accuracy: 0.8385
MultiNomialNB cross-validation accuracy: 0.9769
Kneighbours cross-validation accuracy: 1.0000


In [26]:
gbc = GradientBoostingClassifier(n_estimators=100 , random_state = 2)
gbc.fit(X_train,y_train)
y_pred=gbc.predict(X_test)
accuracy=accuracy_score(y_test , y_pred)
print(accuracy)

0.8360655737704918


In [27]:
mn = MultinomialNB()
mn.fit(X_train,y_train)
y_pred=mn.predict(X_test)
accuracy=accuracy_score(y_test , y_pred)
print(accuracy)

0.9672131147540983


In [28]:
import os

# Create directory if it doesn't exist
if not os.path.exists('model'):
    os.makedirs('model')


In [29]:
import pickle

pickle.dump(gbc, open('model/gbc.pkl','wb'))
pickle.dump(mn, open('model/mn.pkl','wb'))

In [30]:
#load model

gbc = pickle.load(open("model/gbc.pkl",'rb'))
mn = pickle.load(open("model/mn.pkl",'rb'))

In [31]:
gbc

GradientBoostingClassifier(random_state=2)

In [32]:
mn

MultinomialNB()

In [33]:
X_test.iloc[1].values.reshape(1,-1)  #test1

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [34]:
gbc.predict([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

array([34])

In [35]:
mn.predict([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

array([34])

In [36]:
X_test.iloc[7].values.reshape(1,-1)  #test 2

array([[1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [37]:
gbc.predict([[1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

array([15])

In [38]:
mn.predict([[1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

array([15])

NOW MAKING RECOMMENDATION AND PREDICTION

In [39]:
#load few data set
precaution = pd.read_csv("/content/drive/MyDrive/MediSense/precautions_df.csv")
workout = pd.read_csv("/content/drive/MyDrive/MediSense/workout_df.csv")
medication=pd.read_csv("/content/drive/MyDrive/MediSense/medications.csv")
diets=pd.read_csv("/content/drive/MyDrive/MediSense/diets.csv")
description=pd.read_csv("/content/drive/MyDrive/MediSense/description.csv")


In [40]:
#helper function

def helper(dis):
    descr = description[description['Disease']==dis]['Description']
    descr = " ".join({ w for w in descr})

    pre = precaution[precaution['Disease'] == dis][['Precaution_1', 'Precaution_2', 'Precaution_2', 'Precaution_3', 'Precaution_4']]
    pre = [col for col in pre.values]

    die = diets[diets['Disease']==dis]['Diet']
    die = [die for die in die.values]
    work = workout[workout['disease']==dis]['workout']

    med = medication[medication['Disease']==dis]['Medication']
    med = [med for med in med.values]

    return descr , pre , die , med , work

symptom_dict = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}
diseases_list = {15: 'Fungal infection', 20: 'Hepatitis C', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 21: 'Hepatitis D', 19: 'Hepatitis B', 4: 'Allergy', 40: 'hepatitis A', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 27: 'Impetigo'}


In [41]:
def get_predicted_value(patient_symptoms):
    input_vector = np.zeros(len(symptom_dict))
    for item in patient_symptoms:
        input_vector[symptom_dict[item]]=1
    return diseases_list[gbc.predict([input_vector])[0]]

In [43]:
symptoms = input('Enter Your Symptopms : ')
user_symptoms = [s for s in symptoms.split(',')]
user_symptoms = [sym.strip("[]'") for sym in user_symptoms]

predicted_disease = get_predicted_value(user_symptoms)
descr, pre, die , med, work = helper(predicted_disease)

#result
print('Predicted disease  :', predicted_disease)
print('description : ', descr)
print('-----------------------------precautions-------------------------------')
i=1
for j in pre[0]:
    print(i, ':',j)
    i+=1
print('--------------------------------diets-----------------------------------')
for i in die:
    print(i)
print('-----------------------------medication---------------------------------')
i=1
for j in med:
    print(i,":",j)
    i+=1
print('------------------------------workout-----------------------------------')
i=1
for j in work:
  print(i, ":", j)
  i+=1

Enter Your Symptopms : stomach_pain,continuous_sneezing
Predicted disease  : GERD
description :  GERD (Gastroesophageal Reflux Disease) is a digestive disorder that affects the lower esophageal sphincter.
-----------------------------precautions-------------------------------
1 : avoid fatty spicy food
2 : avoid lying down after eating
3 : avoid lying down after eating
4 : maintain healthy weight
5 : exercise
--------------------------------diets-----------------------------------
['Low-Acid Diet', 'Fiber-rich foods', 'Ginger', 'Licorice', 'Aloe vera juice']
-----------------------------medication---------------------------------
1 : ['Proton Pump Inhibitors (PPIs)', 'H2 Blockers', 'Antacids', 'Prokinetics', 'Antibiotics']
------------------------------workout-----------------------------------
1 : Consume smaller meals
2 : Avoid trigger foods (spicy, fatty)
3 : Eat high-fiber foods
4 : Limit caffeine and alcohol
5 : Chew food thoroughly
6 : Avoid late-night eating
7 : Consume non-citr